### ISSUE TITLE
npm error deploy  kanvan-ui

### ISSUE THREAD

**Issue by hzaratec** [wkrzywiec/kanban-board#12]
Hi,  i clone your project to use the kanvan board    (I run the project on Mac and Ubunut virtual Machine x86 architecture), but when i type docker-compose up the step 6  on the first docker file fails as follow:

Step 6/10 : RUN npm run build
 ---> Running in 8d05f88f96ce

> kanban-ui@0.0.0 build /usr/src/app
> ng build --prod

Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(es5BrowserSupport).
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kanban-ui@0.0.0 build: `ng build --prod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kanban-ui@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-28T14_36_37_649Z-debug.log
ERROR: Service 'kanban-ui' failed to build: The command '/bin/sh -c npm run build' returned a non-zero code: 1

Thanks a lot for your attention, and i wait some idea of solve the error.

**Comment by wkrzywiec** [comment]
Hi Henry,

Thanks for catching it! I've build this project a week or so and everything went fine. But the issue should be now fixed (at least works for me ;))

In short, the issue was as it's described here - https://stackoverflow.com/questions/43127863/node-update-a-specific-package and here - https://codippa.com/how-to-resolve-data-path-should-not-have-additional-propertieses5browsersupport-error-in-angular/ .

 I've removed one option from `angular.json` file, to make it work. It's not ideal, coz we lose support for older browsers, but this application is only for education purposes I've decided to keep it that way, not to mess with versions of Angular libraries.

Please let me know if it's solved your problem.

**Comment by hzaratec** [comment]
Hi  @wkrzywiec , The answer is really clear and precise,  works really  fine, I really appreciate your help. Thanks a lot
